name: Merge to Master

on:
  push:
    branches:
      - master

jobs:
  notify-success:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
